dataset:
  # select data source - one of load_counts, sim_cosmic, sim_parametric
  # any parameters for non-selected data sources will be ignored
  dataset_sel: load_counts

  load_counts:
    data_seed: 97
    counts_fp: data/mutation_types_raw_counts.csv
    annotation_fp: data/pcawg_cancer_types.csv
    annotation_subset: ["Breast","Prostate","Kidney","Panc"]

  sim_from_sigs:
    sig_defs_fp: data/COSMIC_v3.2_SBS_GRCh37.txt
    data_seed: 42
    sim_S: 100
    sim_N: 5000
    sim_I: 4
    sim_tau_hyperprior: 0.1

  sim_parametric:
    data_seed: 42
    sim_J: 3
    sim_K: 3
    sim_S: 100
    sim_N: 10000
    sim_alpha_bias: 0.05
    sim_psi_bias: 1
    sim_gamma_bias: 0.1
    sim_beta_bias: 1

model:
  model_sel: tandtiss_lda
  model_seed: 42
  J: 10
  K: 8
  alpha_bias: 1
  psi_bias: 0.1
  gamma_bias: 0.5
  beta_bias: 1
  init_strategy: kmeans
  #log_every: 10000

pymc3:
  n: 10000
  method: advi
  random_seed: 34
  #obj_optimizer: [pm.adam, pm.sgd, pm.adagrad, pm.adadelta]
  #more_obj_params: [learning_rate=0.1]
        
        
        
        
        
        
        
        
    