sim_data.py:
  sim_parametric: 
    seed: 42
    J: 3
    K: 3
    S: 100
    N: 10000
    alpha_bias: 0.05
    psi_bias: 1
    gamma_bias: 0.1
    beta_bias: 1

    
parametric_mix.py:
    fit_collapsed_model:
        J: 6
        K: 6
        alpha_bias: 0.05
        psi_bias: 1
        gamma_bias: 0.1
        beta_bias: 1
        seed: 42
        n_steps: 50000

    
    cbs:
        # sparse logging will speed up training 
        log_every: 10000
        
    
