fit_pcawg.py:
    load_counts:
        counts_fn: 'mutation_types_raw_counts.csv'
        types_fn: 'pcawg_cancer_types.csv'
        type_subset: ['Skin-Melanoma', 'Head-SCC', 'Bladder-TCC']
    
    fit_collapsed_model:
        J: 5
        K: 5
        alpha_bias: 0.05
        psi_bias: 1
        gamma_bias: 1
        beta_bias: 1
        seed: 42
        n_steps: 50000
    
    cbs:
        # sparse logging will speed up training 
        log_every: 10000
        
    
